### ISSUE TITLE
Adding super ellipse support without CSS PaintWorklet Api.

### ISSUE THREAD

**Issue by KDSbami** [KDSbami/manga-reader#13]
Need to create better implementation of super ellipses for UI rounding and improved friendliness of the design.

Reference:

[**Super Ellipse Generator**](https://observablehq.com/@tomwhite/superellipse-generator)

**Comment by sidharthmirch** [comment]
1. Maintain eccentricity between points
    - eccentricity -> constant ratio of focus to any point
2. Plot path using:
![equation](http://www.sciweavers.org/upload/Tex2Img_1630866043/eqn.png)
    - where half width & half height are of the polygon being drawn 

```latex
\frac{1}
{\frac{cos\theta}{\textit{half width}}^\textit{eccentricity}
+ \frac{sin\theta}{\textit{half height}}^\textit{eccentricity}}^\frac{1}{\textit{eccentricity}}
```

Example implementation:
```js
for (let theta = 0.0; theta < 2pi; theta += 2pi / resolution) {
  sineTheta = Math.sin(theta);
  cosineTheta = Math.cos(theta);
  r = Math.pow(1 / (Math.pow(Math.abs(cosineTheta) / halfWidth, eccentricity)
            + Math.pow(Math.abs(sineTheta) / halfHeight, eccentricity)), 1 / eccentricity);
  path.lineTo((float) (centreX + r * cosineTheta), (float) (centreY + r * sineTheta));
}
```

**Comment by KDSbami** [comment]
Updation of Tailwind CSS to [v2.2](https://blog.tailwindcss.com/tailwindcss-2-2) will give access to pseudo-elements after and before. That should be a faster implementation for this. 

- Adding a string builder function that auto-manages radius and width should do the trick.

**Comment by sidharthmirch** [comment]
#14
