### ISSUE TITLE
Building post search Ui&UX 

### ISSUE THREAD

**Issue by KDSbami** [KDSbami/manga-reader#17]
TODO:
- [x] #25
- [x] #26
- [x] #27

**Requirements -** 

- scaleable page with router query support
- URL query manipulation should translate to pure UI & UX changes.

**Comment by sidharthmirch** [comment]
Working in results branch

**Comment by sidharthmirch** [comment]
see link-router
https://github.com/KDSbami/manga-reader/tree/link-router

**Comment by sidharthmirch** [comment]
I think we should only pass query onSubmit, and maybe pass onInput to autocomplete API
thoughts @KDSbami ?

**Comment by sidharthmirch** [comment]
6fbeff7

**Comment by sidharthmirch** [comment]
https://support.google.com/chrome/answer/10490587?hl=en
- nginx

**Comment by sidharthmirch** [comment]
c062566

**Comment by KDSbami** [comment]
[url]/search?q=[search data], if a user types this in the browser it should also work. the current implementation only works the other way around.

1. Make the search component dumb so that it doesn't know what to do but display the text passed to it or pass the displayed text back. 
![search issue](https://user-images.githubusercontent.com/44073600/150463205-ecf8b729-c88d-4fa9-9c1a-a90ae78c5482.jpg)
2. The business logic of what to do with that search information needs to be handled by the page search.
3. Remove the development containers from the search page since it's a production entity.
![dev component](https://user-images.githubusercontent.com/44073600/150463369-5a9acada-3864-48c1-89d6-92a283493d97.jpg)
