### ISSUE TITLE
Populating search page with metadata

### ISSUE THREAD

**Issue by sidharthmirch** [KDSbami/manga-reader#36]
- [x] Populate manga names
- [x] Fetch cover url
- [x] Populate covers

Data is now populating, but we have an underlying issue with `<CardContainer>` for text formatting:
<img width="1433" alt="Screenshot 2022-01-22 at 5 08 05 PM" src="https://user-images.githubusercontent.com/32238869/150636976-a8955295-1a6d-4383-825c-d68f5162ff33.png">

@KDSbami should I leave the text issue and we handle it in #23 ?

**Comment by sidharthmirch** [comment]
See in a4b6499 https://github.com/KDSbami/manga-reader/tree/search-populate

**Comment by KDSbami** [comment]
Yes sure, lets handle component specific issues in a seperate issue.
