### ISSUE TITLE
Manga Showcase page functionality

### ISSUE THREAD

**Issue by KDSbami** [KDSbami/manga-reader#49]
The page shows manga-specific details.
User-experience: Page will be completely generated from URL alone. Query needs to include params that define everything needed to parse the data and show all desired requirements of the user.

example: 
[url]/manga?service=_**mangadex**_&mangaid=_**[mangadex id for the manga selected]**_
_Note: this is under the assumption that these 2 params can populate more can be added for improved functionality_ 

- [x] #50

- [x] #51

**Comment by sidharthmirch** [comment]
will handle this with #54

**Comment by KDSbami** [comment]
> will handle this with #54 

Its a separate issue. Lets handle it separately for easier lifecycle management.

**Comment by sidharthmirch** [comment]
- Process and sanitize markdown
https://www.npmjs.com/package/snarkdown
