### ISSUE TITLE
Average colouring technique for image background.

### ISSUE THREAD

**Issue by KDSbami** [KDSbami/manga-reader#7]
- **Test different averaging techniques and their results for the thumbnail component.**
  1.  common background colour for the whole image.
  2. edge by edge basis gradient colour.

- **Remove Async get color and use getColor so that we can reliably color all image backgrounds and not have** [CORS issue](https://github.com/fast-average-color/fast-average-color#unhandled-rejection-securityerror-the-operation-is-insecure)

**Comment by KDSbami** [comment]
Remove Async get color and use getColor so that we can reliably color all image backgrounds and not have CORS issue

**Comment by sidharthmirch** [comment]
**_References_**

- [Gradient](https://github.com/fast-average-color/examples/blob/master/dist/gradient.js)
- [getColor](https://github.com/fast-average-color/fast-average-color/blob/master/docs/api.md#getcolorresource-options)

**Comment by sidharthmirch** [comment]
Solved in #12
